import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import * as simpleIcons from "simple-icons";

const EXTRA_SLUGS = ["github"];

function slugToExportName(slug: string): string {
  return "si" + slug.charAt(0).toUpperCase() + slug.slice(1);
}

function buildOutput(slugs: string[]): string {
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/generate-icons.ts — do not edit. Run: npm run generate:icons",
    "import {",
  ];

  for (const slug of slugs) {
    lines.push(`  ${slugToExportName(slug)},`);
  }

  lines.push('} from "simple-icons";');
  lines.push("");
  lines.push("export const iconBySlug: Record<string, { path: string }> = {");

  for (const slug of slugs) {
    lines.push(`  ${slug}: ${slugToExportName(slug)},`);
  }

  lines.push("};");
  lines.push("");

  return lines.join("\n");
}

function main(): void {
  const toolsPath = fileURLToPath(
    new URL("../src/catalog/tools.json", import.meta.url),
  );
  const tools = JSON.parse(readFileSync(toolsPath, "utf8")) as Record<
    string,
    { iconSlug?: string }
  >;

  const toolSlugs = Object.values(tools)
    .map((t) => t.iconSlug)
    .filter((s): s is string => typeof s === "string");

  const allSlugs = [...new Set([...toolSlugs, ...EXTRA_SLUGS])].sort();

  // Validate all slugs exist in simple-icons
  const bad: string[] = [];
  for (const slug of allSlugs) {
    const key = slugToExportName(slug);
    if (!(key in (simpleIcons as Record<string, unknown>))) {
      bad.push(`${slug} (looked up as ${key})`);
    }
  }
  if (bad.length) {
    console.error(
      `generate-icons: the following slugs were not found in simple-icons:\n  ${bad.join("\n  ")}\n\nFix or remove them from src/catalog/tools.json or the EXTRA_SLUGS list.`,
    );
    process.exit(1);
  }

  const output = buildOutput(allSlugs);

  const outPath = fileURLToPath(
    new URL("../src/lib/icons.generated.ts", import.meta.url),
  );
  writeFileSync(outPath, output, "utf8");
  console.log(
    `generate-icons: wrote ${allSlugs.length} icons to src/lib/icons.generated.ts`,
  );
}

main();
