import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import * as simpleIcons from "simple-icons";
import {
  archetypesFileSchema,
  toolsFileSchema,
  protocolsFileSchema,
} from "../src/lib/catalog-schema";

const errors: string[] = [];

function load(path: string): unknown {
  return JSON.parse(
    readFileSync(new URL(`../src/catalog/${path}`, import.meta.url), "utf8"),
  );
}

function slugExists(slug: string): boolean {
  const key = "si" + slug.charAt(0).toUpperCase() + slug.slice(1);
  return key in (simpleIcons as Record<string, unknown>);
}

const archetypesResult = archetypesFileSchema.safeParse(
  load("archetypes.json"),
);
const toolsResult = toolsFileSchema.safeParse(load("tools.json"));
const protocolsResult = protocolsFileSchema.safeParse(load("protocols.json"));

for (const [name, result] of [
  ["archetypes.json", archetypesResult],
  ["tools.json", toolsResult],
  ["protocols.json", protocolsResult],
] as const) {
  if (!result.success) {
    for (const issue of result.error.issues) {
      errors.push(`${name} -> ${issue.path.join(".")}: ${issue.message}`);
    }
  }
}

// Cross-checks need schema-valid data; if zod already failed, fix those errors first.
if (archetypesResult.success && toolsResult.success) {
  const archetypes = archetypesResult.data;
  const tools = toolsResult.data;
  for (const [key, tool] of Object.entries(tools)) {
    if (!archetypes[tool.archetype]) {
      errors.push(
        `tools.json -> ${key}: unknown archetype "${tool.archetype}"`,
      );
    }
    if (tool.iconSlug && !slugExists(tool.iconSlug)) {
      errors.push(
        `tools.json -> ${key}: iconSlug "${tool.iconSlug}" not found in simple-icons (remove it or use svgPath)`,
      );
    }
  }
  for (const [key, a] of Object.entries(archetypes)) {
    if (!tools[a.defaultTool]) {
      errors.push(
        `archetypes.json -> ${key}: defaultTool "${a.defaultTool}" not in tools.json`,
      );
    } else if (tools[a.defaultTool].archetype !== key) {
      errors.push(
        `archetypes.json -> ${key}: defaultTool "${a.defaultTool}" belongs to a different archetype`,
      );
    }
  }
}

// Check that src/lib/icons.generated.ts is up to date
{
  const EXTRA_SLUGS = ["github"];

  function slugToExportName(slug: string): string {
    return "si" + slug.charAt(0).toUpperCase() + slug.slice(1);
  }

  function buildExpectedOutput(slugs: string[]): string {
    const lines: string[] = [
      "// AUTO-GENERATED by scripts/generate-icons.ts — do not edit. Run: npm run generate:icons",
      "import {",
    ];
    for (const slug of slugs) {
      lines.push(`  ${slugToExportName(slug)},`);
    }
    lines.push('} from "simple-icons";');
    lines.push("");
    lines.push("export const iconBySlug: Record<string, { path: string }> = {");
    for (const slug of slugs) {
      lines.push(`  ${slug}: ${slugToExportName(slug)},`);
    }
    lines.push("};");
    lines.push("");
    return lines.join("\n");
  }

  // Collect slugs from validated tools (or raw file if validation failed)
  const rawTools = load("tools.json") as Record<string, { iconSlug?: string }>;
  const toolSlugs = Object.values(rawTools)
    .map((t) => t.iconSlug)
    .filter((s): s is string => typeof s === "string");
  const expectedSlugs = [...new Set([...toolSlugs, ...EXTRA_SLUGS])].sort();
  const expectedContent = buildExpectedOutput(expectedSlugs);

  const generatedPath = fileURLToPath(
    new URL("../src/lib/icons.generated.ts", import.meta.url),
  );
  let actualContent: string;
  try {
    actualContent = readFileSync(generatedPath, "utf8");
  } catch {
    actualContent = "";
  }

  if (actualContent !== expectedContent) {
    errors.push(
      "src/lib/icons.generated.ts is out of date — run: npm run generate:icons",
    );
  }
}

if (errors.length) {
  console.error(
    `Catalog validation failed:\n${errors.map((e) => `  ✗ ${e}`).join("\n")}`,
  );
  process.exit(1);
}
console.log("Catalog valid ✓");
